// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBanGiay.Data;

#nullable disable

namespace QuanLyBanGiay.Migrations
{
    [DbContext(typeof(QLBGDbContext))]
    partial class QLBGDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyBanGiay.Data.Giay", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiGiayID")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuongHieuID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LoaiGiayID");

                    b.HasIndex("ThuongHieuID");

                    b.ToTable("Giays");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.HoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChuHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.HoaDon_ChiTiet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DonGiaBan")
                        .HasColumnType("int");

                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<int>("SizeGiayID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("SizeGiayID");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.LoaiGiay", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LoaiGiays");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.MauSac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MauSacs");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.NhaCungCap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhaCungCaps");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuyenHan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.PhieuNhap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhaCungCapID")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NhaCungCapID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("PhieuNhaps");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.PhieuNhap_ChiTiet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DonGiaNhap")
                        .HasColumnType("int");

                    b.Property<int>("PhieuNhapID")
                        .HasColumnType("int");

                    b.Property<int>("SizeGiayID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PhieuNhapID");

                    b.HasIndex("SizeGiayID");

                    b.ToTable("PhieuNhapChiTiets");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.SizeGiay", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("GiayID")
                        .HasColumnType("int");

                    b.Property<int>("MauSacID")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GiayID");

                    b.HasIndex("MauSacID");

                    b.ToTable("SizeGiays");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.ThuongHieu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ThuongHieus");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.Giay", b =>
                {
                    b.HasOne("QuanLyBanGiay.Data.LoaiGiay", "LoaiGiay")
                        .WithMany("Giays")
                        .HasForeignKey("LoaiGiayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanGiay.Data.ThuongHieu", "ThuongHieu")
                        .WithMany("Giays")
                        .HasForeignKey("ThuongHieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiGiay");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.HoaDon", b =>
                {
                    b.HasOne("QuanLyBanGiay.Data.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanGiay.Data.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.HoaDon_ChiTiet", b =>
                {
                    b.HasOne("QuanLyBanGiay.Data.HoaDon", "HoaDon")
                        .WithMany("HoaDon_ChiTiets")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanGiay.Data.SizeGiay", "SizeGiay")
                        .WithMany()
                        .HasForeignKey("SizeGiayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SizeGiay");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyBanGiay.Data.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("NhaCungCapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanGiay.Data.NhanVien", "NhanVien")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.PhieuNhap_ChiTiet", b =>
                {
                    b.HasOne("QuanLyBanGiay.Data.PhieuNhap", "PhieuNhap")
                        .WithMany("PhieuNhapChiTiets")
                        .HasForeignKey("PhieuNhapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanGiay.Data.SizeGiay", "SizeGiay")
                        .WithMany()
                        .HasForeignKey("SizeGiayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("SizeGiay");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.SizeGiay", b =>
                {
                    b.HasOne("QuanLyBanGiay.Data.Giay", "Giay")
                        .WithMany("SizeGiays")
                        .HasForeignKey("GiayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanGiay.Data.MauSac", "MauSac")
                        .WithMany("SizeGiays")
                        .HasForeignKey("MauSacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Giay");

                    b.Navigation("MauSac");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.Giay", b =>
                {
                    b.Navigation("SizeGiays");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.HoaDon", b =>
                {
                    b.Navigation("HoaDon_ChiTiets");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.LoaiGiay", b =>
                {
                    b.Navigation("Giays");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.MauSac", b =>
                {
                    b.Navigation("SizeGiays");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.PhieuNhap", b =>
                {
                    b.Navigation("PhieuNhapChiTiets");
                });

            modelBuilder.Entity("QuanLyBanGiay.Data.ThuongHieu", b =>
                {
                    b.Navigation("Giays");
                });
#pragma warning restore 612, 618
        }
    }
}
